---
- name: Create machine credentials
  ansible.controller.credential:
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs }}"
    name: "{{ item.name }}"
    credential_type: Machine
    organization: "{{ organization_name }}"
    description: "Private SSH key"
    inputs:
      ssh_key_data: "{{ item.inputs.ssh_key_data }}"
  loop: "{{ vault_credentials }}"
  when: item.type == "Machine" and item.inputs.ssh_key_data | length > 0
  no_log: true

