---
- name: Set survey var
  ansible.builtin.set_fact:
    survey_enabled: "{{ survey.survey_enabled | default('no') }}"
    survey_spec: "{{ survey.survey_spec | default({}) }}"

- name: Create job template(s)
  ansible.controller.job_template:
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs }}"
    credentials: "{{ credential_names | default([]) }}"
    description: "Job template for {{ project_name }} running {{ item | basename }}"
    execution_environment: "{{ execution_environment | default('Control Plane Execution Environment') }}"
#        extra_vars:
#          target_hosts: dev_secondary
    inventory: "{{ project_name }}-inventory"
    job_type: run
    name: "{{ project_name }} - {{ item | basename | regex_replace('(\\.yaml|\\.yml)$', '') }}" 
    organization: "{{ organization_name }}"
    playbook: "{{ item }}"
    project: "{{ project_name }}"
    survey_enabled: "{{ survey_enabled }}"
    survey_spec: "{{ survey_spec }}"
  loop: "{{ playbook_file_paths }}"

