---
- name: Create a Source Control (Git) credential
  ansible.controller.credential:
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs }}"
    credential_type: Source Control
    description: "Git credential for {{ project_name }}"
    inputs:
      password: "{{ item.inputs.token }}"
      username: "aap-user" # any string value will work
    name: "{{ project_name }}-git-credential"
    organization: "{{ organization_name }}"
  loop: "{{ git_credentials }}"
  when: item.name == project_name and item.inputs.token | length > 0
  no_log: true

