---
- name: Create project
  ansible.controller.project:
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs }}"
    name: "{{ project_name }}"
    organization: "{{ organization_name }}"
    scm_url: "{{ scm_url }}"
    scm_type: git
    scm_branch: "{{ scm_branch }}"
    scm_credential: "{{ project_name }}-git-credential"
    scm_update_on_launch: true
