
---
- name: Verify if the inventory exists
  ansible.controller.export:
    # Default
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs }}"
    # CHANGEME
    inventory: "{{ project_name }}-inventory"
  register: get_inv

- debug:
    var: get_inv

- name: Create a job template
  ansible.controller.job_template:
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs }}"
#        credentials:
#        - nexus-token-vault
#        - zeng-ocs-cics-id-rsa
    description: "Job template for {{ project_name }}"
    execution_environment: Control Plane Execution Environment
#        extra_vars:
#          target_hosts: dev_secondary
    inventory: "{{ project_name }}-inventory"
    job_type: run
    name: "{{ job_template_name }}"
    organization: "{{ organization_name }}"
    playbook: "{{ playbook_file_name }}"
    prevent_instance_group_fallback: false
    project: "{{ project_name }}"
  when: get_inv.assets.inventory[0] | length > 0
