
---
- name: Create a Source Control credential
  ansible.controller.credential:
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs }}"
    credential_type: Source Control
    description: "Git credential for {{ project_name }}"
    inputs:
      password: "{{ test_gitlab_token }}"
      username: "aap-user" # any string value will work
    name: "{{ credential_name }}"
    organization: "{{ organization_name }}"

