---
- name: Fetch private key
  ansible.builtin.slurp:
    src: ~/.ssh/id_rsa
  register: ssh_key

- name: Test credentials
  ansible.controller.credentials:
    # Default
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs }}"
    # Change below
    name: Host SSH Key
    credential_type: Machine
    organization: FTS Mainframe
    description: "Private SSH key"
    inputs:
      ssh_key_data: "{{ ssh_key['content'] | b64decode }}"
          
