---
# tasks file for create_new_aap_resources
- name: Create credentials
  include_tasks: create_credentials.yml
  
- name: Create projects
  include_tasks: 
    file: create_projects.yml
    apply:
      tags: projects
  tags: projects
  
- name: Create inventories
  include_tasks: create_inventories.yml

- name: Create job templates
  include_tasks: 
    file: create_job_templates.yml
    apply:
      tags: job_templates
  tags: job_templates

